//IMPORTANT: This file is AUTO-GENERATED by the KSP protocol generator.
//Do NOT edit it by hand!
//1. Frame format (header / type / CRC / field order) and all send/receive
//   functions are defined by the KSP project;
//2. Manual edits will be overwritten the next time KSP regenerates this file;
//3. To change the protocol, edit the KSP side and regenerate, then sync the
//   generated output back into this file;
//4. Before debugging, make sure this file matches the latest KSP output.
//Generated by: @author diling @date Wed Sep 02 15:38:06 CST 2026
#pragma message("[DLX Protocol] Using protocol")
#include <stdint.h>
#include "dlx_bytebuffer.hpp"
using namespace dlx;
struct UnBlock {
    ByteBuffer* buf;
    UnBlock(ByteBuffer* buffer): buf(buffer){}
    uint8_t param(){return buf->read_at<uint8_t>(0);}
};
typedef void(*UnBlockCallbackFunctionType)(UnBlock*,void *);
struct TargetThrottleValue {
    ByteBuffer* buf;
    TargetThrottleValue(ByteBuffer* buffer): buf(buffer){}
    uint16_t data(uint16_t index){return buf->read_le_at<uint16_t>(0+index*2); }
};
typedef void(*TargetThrottleValueCallbackFunctionType)(TargetThrottleValue*,void *);
struct DrawFrameSlice {
    ByteBuffer* buf;
    DrawFrameSlice(ByteBuffer* buffer): buf(buffer){}
    uint16_t data(uint16_t index){return buf->read_le_at<uint16_t>(0+index*2); }
};
typedef void(*DrawFrameSliceCallbackFunctionType)(DrawFrameSlice*,void *);
struct ControlToFlight {
    ByteBuffer* buf;
    ControlToFlight(ByteBuffer* buffer): buf(buffer){}
    float targetPitch(){return buf->read_at<float>(0);}
    float targetRoll(){return buf->read_at<float>(4);}
    float targetHeight(){return buf->read_at<float>(8);}
    uint16_t counter(){return buf->read_at<uint16_t>(12);}
    uint16_t command(){return buf->read_at<uint16_t>(14);}
    uint16_t motor0(){return buf->read_at<uint16_t>(16);}
    uint16_t motor1(){return buf->read_at<uint16_t>(18);}
    uint16_t motor2(){return buf->read_at<uint16_t>(20);}
    uint16_t motor3(){return buf->read_at<uint16_t>(22);}
    float throttle(){return buf->read_at<float>(24);}
    uint16_t blank(){return buf->read_at<uint16_t>(28);}
};
typedef void(*ControlToFlightCallbackFunctionType)(ControlToFlight*,void *);
struct FlightCoreStatus {
    ByteBuffer* buf;
    FlightCoreStatus(ByteBuffer* buffer): buf(buffer){}
    float Quaternion0(){return buf->read_at<float>(0);}
    float Quaternion1(){return buf->read_at<float>(4);}
    float Quaternion2(){return buf->read_at<float>(8);}
    float Quaternion3(){return buf->read_at<float>(12);}
    uint16_t motor0(){return buf->read_at<uint16_t>(16);}
    uint16_t motor1(){return buf->read_at<uint16_t>(18);}
    uint16_t motor2(){return buf->read_at<uint16_t>(20);}
    uint16_t motor3(){return buf->read_at<uint16_t>(22);}
    float height(){return buf->read_at<float>(24);}
    uint16_t error(){return buf->read_at<uint16_t>(28);}
};
typedef void(*FlightCoreStatusCallbackFunctionType)(FlightCoreStatus*,void *);

struct DLX_ProtocolBuffer {
    uint8_t crc4_itu(uint8_t *data, uint16_t length){
        uint8_t i;
        uint8_t crc = 0;                    // Initial value
        while(length--)
        {
            crc ^= *data++;                 // crc ^= *data; data++;
            for (i = 0; i < 8; ++i)
            {
                if (crc & 1)
                    crc = (crc >> 1) ^ 0x0C;// 0x0C = (reverse 0x03)>>(8-4)
                else
                    crc = (crc >> 1);
            }
        }
        return crc;
    }
    ByteBuffer& buffer;
    RingByteBuffer* source;
    ByteBuffer* frame;
    DLX_ProtocolBuffer(ByteBuffer& buffer):buffer(buffer){ }
    DLX_ProtocolBuffer(ByteBuffer& buffer,RingByteBuffer* source,ByteBuffer* frame):buffer(buffer),source(source),frame(frame){ }

UnBlockCallbackFunctionType UnBlockCallbackFunction=nullptr;
void* UnBlockCallbackFunctionCtx;
void setUnBlockCallbackFunction(UnBlockCallbackFunctionType callback,void * ctx) {
    UnBlockCallbackFunction = callback;
    UnBlockCallbackFunctionCtx = ctx;
}
TargetThrottleValueCallbackFunctionType TargetThrottleValueCallbackFunction=nullptr;
void* TargetThrottleValueCallbackFunctionCtx;
void setTargetThrottleValueCallbackFunction(TargetThrottleValueCallbackFunctionType callback,void * ctx) {
    TargetThrottleValueCallbackFunction = callback;
    TargetThrottleValueCallbackFunctionCtx = ctx;
}
DrawFrameSliceCallbackFunctionType DrawFrameSliceCallbackFunction=nullptr;
void* DrawFrameSliceCallbackFunctionCtx;
void setDrawFrameSliceCallbackFunction(DrawFrameSliceCallbackFunctionType callback,void * ctx) {
    DrawFrameSliceCallbackFunction = callback;
    DrawFrameSliceCallbackFunctionCtx = ctx;
}
ControlToFlightCallbackFunctionType ControlToFlightCallbackFunction=nullptr;
void* ControlToFlightCallbackFunctionCtx;
void setControlToFlightCallbackFunction(ControlToFlightCallbackFunctionType callback,void * ctx) {
    ControlToFlightCallbackFunction = callback;
    ControlToFlightCallbackFunctionCtx = ctx;
}
FlightCoreStatusCallbackFunctionType FlightCoreStatusCallbackFunction=nullptr;
void* FlightCoreStatusCallbackFunctionCtx;
void setFlightCoreStatusCallbackFunction(FlightCoreStatusCallbackFunctionType callback,void * ctx) {
    FlightCoreStatusCallbackFunction = callback;
    FlightCoreStatusCallbackFunctionCtx = ctx;
}
bool DebugCounterW(uint8_t counter) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<3){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write<uint8_t>(counter);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (0<<5) | (crc4_itu(p+2, 1)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool SimpleLogW(int8_t *raw, uint16_t raw_len) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<4 + raw_len * 1){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write<uint16_t>(raw_len);
    buffer.write(reinterpret_cast<uint8_t*>( raw ), raw_len * 1);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (1<<5) | (crc4_itu(p+2, 2 + raw_len * 1)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool UnBlockW(uint8_t param) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<3){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write<uint8_t>(param);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (2<<5) | (crc4_itu(p+2, 1)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool QuatW(float *value) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<18){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write(reinterpret_cast<uint8_t*>( value ), 16);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (3<<5) | (crc4_itu(p+2, 16)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool AccelRawW(uint16_t *data) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<8){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write(reinterpret_cast<uint8_t*>( data ), 6);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (4<<5) | (crc4_itu(p+2, 6)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool GyroRawW(uint16_t *degrees) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<8){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write(reinterpret_cast<uint8_t*>( degrees ), 6);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (5<<5) | (crc4_itu(p+2, 6)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool TargetThrottleValueW(uint16_t *data) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<10){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write(reinterpret_cast<uint8_t*>( data ), 8);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (6<<5) | (crc4_itu(p+2, 8)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool ThrottleValueW(uint16_t *data) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<10){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write(reinterpret_cast<uint8_t*>( data ), 8);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (7<<5) | (crc4_itu(p+2, 8)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool DrawFrameSliceW(uint16_t *data) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<2050){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write(reinterpret_cast<uint8_t*>( data ), 2048);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (8<<5) | (crc4_itu(p+2, 2048)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool ControlToFlightW(float targetPitch, float targetRoll, float targetHeight, uint16_t counter, uint16_t command, uint16_t motor0, uint16_t motor1, uint16_t motor2, uint16_t motor3, float throttle, uint16_t blank) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<32){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write<float>(targetPitch);
    buffer.write<float>(targetRoll);
    buffer.write<float>(targetHeight);
    buffer.write<uint16_t>(counter);
    buffer.write<uint16_t>(command);
    buffer.write<uint16_t>(motor0);
    buffer.write<uint16_t>(motor1);
    buffer.write<uint16_t>(motor2);
    buffer.write<uint16_t>(motor3);
    buffer.write<float>(throttle);
    buffer.write<uint16_t>(blank);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (9<<5) | (crc4_itu(p+2, 30)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
bool FlightCoreStatusW(float Quaternion0, float Quaternion1, float Quaternion2, float Quaternion3, uint16_t motor0, uint16_t motor1, uint16_t motor2, uint16_t motor3, float height, uint16_t error) {
    uint8_t *p = buffer.cur;
    if(buffer.remaining()<32){return false;}
    buffer.write<uint16_t>(0); // DUMMY
    buffer.write<float>(Quaternion0);
    buffer.write<float>(Quaternion1);
    buffer.write<float>(Quaternion2);
    buffer.write<float>(Quaternion3);
    buffer.write<uint16_t>(motor0);
    buffer.write<uint16_t>(motor1);
    buffer.write<uint16_t>(motor2);
    buffer.write<uint16_t>(motor3);
    buffer.write<float>(height);
    buffer.write<uint16_t>(error);
    uint16_t dlx_header = static_cast<uint16_t>(((1<<15) | (10<<5) | (crc4_itu(p+2, 30)<<1)));
    *p     = (dlx_header >> 8) & 0xff;
    *(p+1) = dlx_header & 0xff;
    return true;
}
//最多不得超过16个可变长字段
bool check() {
    if (source->available() < 2) {return false;}
    uint16_t head = source->peek_be<uint16_t>();
    uint16_t type = (head >> 5) & 0x3ff;
    uint8_t crc = (head >> 1) & 0xf;
    switch(type) {
case 2: {
    uint16_t len = 1;
    if(source->available()<len+2){return false;}
    source->skip(2);
    source->read(frame->src,len);
    if(crc != crc4_itu(frame->src,len)){return false;}
    UnBlock __tmp(frame);
    if(UnBlockCallbackFunction!=nullptr) UnBlockCallbackFunction(&__tmp,UnBlockCallbackFunctionCtx);
    break;
}

case 6: {
    uint16_t len = 8;
    if(source->available()<len+2){return false;}
    source->skip(2);
    source->read(frame->src,len);
    if(crc != crc4_itu(frame->src,len)){return false;}
    TargetThrottleValue __tmp(frame);
    if(TargetThrottleValueCallbackFunction!=nullptr) TargetThrottleValueCallbackFunction(&__tmp,TargetThrottleValueCallbackFunctionCtx);
    break;
}

case 8: {
    uint16_t len = 2048;
    if(source->available()<len+2){return false;}
    source->skip(2);
    source->read(frame->src,len);
    if(crc != crc4_itu(frame->src,len)){return false;}
    DrawFrameSlice __tmp(frame);
    if(DrawFrameSliceCallbackFunction!=nullptr) DrawFrameSliceCallbackFunction(&__tmp,DrawFrameSliceCallbackFunctionCtx);
    break;
}

case 9: {
    uint16_t len = 30;
    if(source->available()<len+2){return false;}
    source->skip(2);
    source->read(frame->src,len);
    if(crc != crc4_itu(frame->src,len)){return false;}
    ControlToFlight __tmp(frame);
    if(ControlToFlightCallbackFunction!=nullptr) ControlToFlightCallbackFunction(&__tmp,ControlToFlightCallbackFunctionCtx);
    break;
}

case 10: {
    uint16_t len = 30;
    if(source->available()<len+2){return false;}
    source->skip(2);
    source->read(frame->src,len);
    if(crc != crc4_itu(frame->src,len)){return false;}
    FlightCoreStatus __tmp(frame);
    if(FlightCoreStatusCallbackFunction!=nullptr) FlightCoreStatusCallbackFunction(&__tmp,FlightCoreStatusCallbackFunctionCtx);
    break;
}
    default:
        return false;
    }
    return true;
}

};